imports:
  - {resource: parameters.yml}
  - {resource: security.yml}
  - {resource: services.yml}

framework:
  secret: 1234

  router:
    resource: "%kernel.root_dir%/config/routing.yml"
    strict_requirements: ~